apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm
resources:
  - ../../base
  - ../../../../runtimes/llamacpp-arm64
  - httproute.yaml
  - scaledobject.yaml
  - pdb.yaml
  - fallback.yaml
  - retry-policy.yaml
patches:
  - path: patch-resources.yaml
